option to turn on/off adm borders
akariv/wpdx-apps pull request #3
Opened 2022-03-23 14:12 UTC by camilabarca

2022-03-23 21:03 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
> +    this.rpState.show_adm_borders = props.mode === 'adman' ? false : (props.mode === 'staleness' ? false : (this.rpState.show_adm_borders));
don't overwrite the state here - use a local variable.

2022-03-23 21:05 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
> +      this.rpState.map.setLayoutProperty('adm-analysis-borders', 'visibility', 'visible');
you also need to turn them off if show_adm_borders is false and we're not in adman/staleness modes.

2022-03-28 19:02 UTC, akariv requested changes

2022-03-28 19:02 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
>        this.rpState.map.setFilter('adm-analysis-borders', null);
we don't need to clear the filter here, right?

2022-03-28 19:02 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
> +      this.rpState.map.setFilter('adm-analysis-borders', null);
why do you clear the filter here?

2022-03-28 19:02 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
> +      this.rpState.map.setPaintProperty('adm-analysis-borders', 'line-color','#000000');
setting the line color and opacity is not needed if the entire layer is not visible...

2022-03-28 19:02 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
> +    if (!this.rpState.show_adm_borders){
why not use `else` here? or at least `if (!admBorders) {`?

2022-03-29 20:16 UTC, camilabarca commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
>        this.rpState.map.setFilter('adm-analysis-borders', null);
If I don't clear the filter hear the filter from adm analysis stays

2022-03-30 10:05 UTC, akariv requested changes

2022-03-30 10:05 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
> +      this.rpState.map.setLayoutProperty('adm-analysis-borders', 'visibility', 'visible');
what's the point? It gets re-set anyway in line 692 right after this...

2022-03-30 10:07 UTC, akariv commented on projects/wpdx/src/app/rehab-prio/rehab-prio.component.ts
>        this.rpState.map.setFilter('adm-analysis-borders', null);
yes, but note that the filter is made up of adm_level filtering as well as the filter by region.
while we indeed want to show all adm levels, we still want to keep filtering by region...

2022-04-04 13:08 UTC, akariv approved these changes

2022-04-04 13:18 UTC, merged